name: sns_rooster
environment:
  sdk: '^3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  provider: ^6.0.5

  # Network & Data Handling
  http: ^1.1.0
  shared_preferences: ^2.2.1
  jwt_decoder: ^2.0.1 # For decoding JWT tokens

  # UI & Utilities
  intl: ^0.18.1 # For date formatting and internationalization
  flutter_svg: ^2.0.9 # For SVG image rendering
  fl_chart: ^0.65.0 # For charts (e.g., in Admin Dashboard)
  image_picker: ^1.0.4 # For picking images from gallery/camera
  table_calendar: ^3.0.9 # Updated version to resolve dependency issues

  # Database
  # sqflite: ^2.3.0 # Uncomment if you need a local SQLite database
  # path_provider: ^2.1.1 # Required for sqflite to find database path 

flutter:
  uses-material-design: true
  assets:
    - assets/images/default_avatar.png

  # ... rest of the original file content ... 