// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrqjkWAfQqSWBPmKCAxYxs6cjuDEbPZGc',
    appId: '1:901502276055:web:f4f94088120f52dc8f7b92',
    messagingSenderId: '901502276055',
    projectId: 'sns-rooster-8cca5',
    authDomain: 'sns-rooster-8cca5.firebaseapp.com',
    storageBucket: 'sns-rooster-8cca5.firebasestorage.app',
    measurementId: 'G-7QJ3X926H8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWg9ySUE_XSpPF4T5Og1FLoazIZR8Orqg',
    appId: '1:901502276055:android:e6650638399db0978f7b92',
    messagingSenderId: '901502276055',
    projectId: 'sns-rooster-8cca5',
    storageBucket: 'sns-rooster-8cca5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-l666W8SWOZ2qjQYTEZZOMxH3hF7wTAA',
    appId: '1:901502276055:ios:711561b6f01d57e68f7b92',
    messagingSenderId: '901502276055',
    projectId: 'sns-rooster-8cca5',
    storageBucket: 'sns-rooster-8cca5.firebasestorage.app',
    iosBundleId: 'com.example.snsRooster',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-l666W8SWOZ2qjQYTEZZOMxH3hF7wTAA',
    appId: '1:901502276055:ios:711561b6f01d57e68f7b92',
    messagingSenderId: '901502276055',
    projectId: 'sns-rooster-8cca5',
    storageBucket: 'sns-rooster-8cca5.firebasestorage.app',
    iosBundleId: 'com.example.snsRooster',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrqjkWAfQqSWBPmKCAxYxs6cjuDEbPZGc',
    appId: '1:901502276055:web:b6588558695bc61c8f7b92',
    messagingSenderId: '901502276055',
    projectId: 'sns-rooster-8cca5',
    authDomain: 'sns-rooster-8cca5.firebaseapp.com',
    storageBucket: 'sns-rooster-8cca5.firebasestorage.app',
    measurementId: 'G-D3ZXD85DKS',
  );
}
